packages:
  - docs
  - packages/*
  - apps/*
  - examples/*

catalog:
  tsup: 8.5.1
  "@types/node": 22.18.12
  "@vitest/coverage-v8": 4.0.17
  typescript: 5.9.3
  vite: 7.3.1
  vite-tsconfig-paths: 6.0.4
  vitest: 4.0.17
  vitest-fetch-mock: 0.4.5
  zod: 4.3.5
  rimraf: 6.1.2

catalogs:
  eslint:
    eslint: 10.0.0
    "@eslint/eslintrc": 3.3.3
    "@eslint/js": 10.0.1
    typescript-eslint: 8.53.0
    eslint-config-prettier: 10.1.8
    eslint-config-turbo: 2.7.4
    eslint-plugin-prettier: 5.5.5
    eslint-config-next: 16.1.2

onlyBuiltDependencies:
  - esbuild
