packages:
  - docs
  - "packages/*"
  - "apps/*"
  - "examples/*"

catalog:
  typescript: 5.9.3
  vite: 5.2.10
  vite-tsconfig-paths: 4.3.2
  vitest: 1.5.0
  vitest-fetch-mock: ^0.3.0
  "@vitest/coverage-v8": ^1.5.0
