packages:
  - docs
  - packages/*
  - apps/*
  - examples/*

catalog:
  tsup: 8.5.1
  "@types/node": 22.18.12
  "@vitest/coverage-v8": 4.0.16
  typescript: 5.9.3
  vite: 7.3.0
  vite-tsconfig-paths: 6.0.3
  vitest: 4.0.16
  vitest-fetch-mock: 0.4.5
  zod: 4.3.4
  rimraf: 6.1.2

catalogs:
  eslint:
    eslint: 9.39.2
    "@eslint/eslintrc": 3.3.3
    "@eslint/js": 9.39.2
    typescript-eslint: 8.50.1
    eslint-config-prettier: 10.1.8
    eslint-config-turbo: 2.7.2
    eslint-plugin-prettier: 5.5.4
    eslint-config-next: 16.1.1

onlyBuiltDependencies:
  - esbuild
