packages:
  - docs
  - packages/*
  - apps/*
  - examples/*

catalog:
  tsup: 8.5.1
  "@types/node": 22.18.12
  "@vitest/coverage-v8": 4.0.18
  typescript: 5.9.3
  vite: 7.3.1
  vite-tsconfig-paths: 6.1.1
  vitest: 4.0.18
  vitest-fetch-mock: 0.4.5
  zod: 4.3.6
  rimraf: 6.1.2

catalogs:
  eslint:
    eslint: 9.39.2
    "@eslint/eslintrc": 3.3.3
    "@eslint/js": 9.39.2
    typescript-eslint: 8.55.0
    eslint-config-prettier: 10.1.8
    eslint-config-turbo: 2.8.7
    eslint-plugin-prettier: 5.5.5
    eslint-config-next: 16.1.6

onlyBuiltDependencies:
  - esbuild
