packages:
  - docs
  - packages/*
  - apps/*
  - examples/*

catalog:
  tsup: 8.5.0
  "@types/node": 22.18.12
  "@vitest/coverage-v8": 4.0.3
  typescript: 5.9.3
  vite: 7.1.12
  vite-tsconfig-paths: 5.1.4
  vitest: 4.0.3
  vitest-fetch-mock: 0.4.5

onlyBuiltDependencies:
  - esbuild
